version: '3'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: data
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  service:
    build:
      context: .
    ports:
      - "8000:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_NAME=data
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - ./service:/service
    depends_on:
      - postgres

