# Generated by Django 4.2 on 2024-03-29 08:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Не верный формат!', regex='^[1-9][0-9]{3}[A-Z]$')])),
                ('weight', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=1000)])),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state_name', models.CharField(max_length=50)),
                ('zip', models.CharField(db_index=True, max_length=50)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=1000)])),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.car')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_delivery', to='app.location')),
                ('pick_up', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_pick_up', to='app.location')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.location'),
        ),
    ]
